### ISSUE TITLE
error after update.

### ISSUE THREAD

**Issue by SharpBCD** [JorgenVatle/bnr-exchange-history#3]
Error: Unexpected close tag
Line: 16
Column: 79
Char: >
    at error (W:\projects\vhci-crm\backend\node_modules\sax\lib\sax.js:651:10)
    at strictFail (W:\projects\vhci-crm\backend\node_modules\sax\lib\sax.js:677:7)
    at closeTag (W:\projects\vhci-crm\backend\node_modules\sax\lib\sax.js:871:9)
    at SAXParser.write (W:\projects\vhci-crm\backend\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (W:\projects\vhci-crm\backend\node_modules\xml2js\lib\parser.js:323:31)

Was working until 31 of Dec. Now I see it on logs starting 1st of Jan.
Weird... did BNR changed something?

**Comment by JorgenVatle** [comment]
Hey there. 👋

Terribly sorry about the issue there. We hadn't accounted for BNR returning with `HTTP 200 OK` for exchange rates that don't exist. The [`v4.1.1`](https://www.npmjs.com/package/bnr-exchange-history) release should resolve the issue.

It's major release as we have bumped the Node.js version requirement to >=12.0.0. Apart from that, there shouldn't be any breaking changes. 👍
```shell
npm i bnr-exchange-history@4
```
